/**
 * **WF-001–096 逐项源码 / 操作 / 证据映射**（W-R01）——本包的主数据。
 *
 * 每一行把一条能力钉到：实现状态、源码文件、操作语义动词、独立测试证据。
 * 路径**必须真实存在**（由 `wf-mapping.test.ts` 在磁盘上逐条断言）；名称/分组**必须与只读素材
 * 逐字一致**（同上）。
 *
 * 状态判定口径（诚实优先，宁可标低不标高）：
 * - `implemented`：源码模块存在 + 有独立 `*.test.ts` 证据。
 * - `partial`：只覆盖该 WF 的部分子选项，或证据来自间接的 workflow 测试。
 * - `missing`：仓内无对应实现模块（本仓经检索确认）。
 * - `unverified`：有源码但**无**独立自动化证据（如仅 Java 文件、真机层未跑）。
 *
 * 本文件**不 import 任何生产代码**，只描述它在哪里；保持验收独立。
 */

import type { WfMappingRow, WfStatus, WfOperationKind } from './types.js';

/** 构造一行的紧凑助手，避免 96 行对象字面量的噪声。 */
function row(
  wf: string,
  name: string,
  group: string,
  status: WfStatus,
  sources: readonly string[],
  operations: readonly WfOperationKind[],
  evidence: readonly string[],
  note?: string,
): WfMappingRow {
  return note !== undefined
    ? { wf, name, group, status, sources, operations, evidence, note }
    : { wf, name, group, status, sources, operations, evidence };
}

const G_CHAR = '字符格式';
const G_PARA = '段落排版';
const G_STYLE = '样式、列表与组织';
const G_PAGE = '页面与节';
const G_TABLE = '表格';
const G_DRAW = '图片与图形';
const G_REF = '引用、长文与审阅';
const G_FLOW = '编辑与文件工作流';
const G_OTHER = '其他常用内容与校对';

// 常用证据路径别名，集中便于核对。
const E_CHAR_PROPS = 'src/documents/operations/character/properties.test.ts';
const E_CHAR_APPLY = 'src/documents/operations/character/apply.test.ts';
const E_CHAR_REPLACE = 'src/documents/operations/character/replace.test.ts';

export const WF_MAPPING: readonly WfMappingRow[] = [
  // ── 3.1 字符格式（W1） ─────────────────────────────────────────────
  row('WF-001', '加粗及取消加粗', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts', 'src/documents/operations/character/apply.ts'],
    ['set', 'toggle', 'unset'], [E_CHAR_PROPS, E_CHAR_APPLY]),
  row('WF-002', '斜体及取消斜体', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'toggle', 'unset'], [E_CHAR_PROPS]),
  row('WF-003', '下划线', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'toggle', 'unset'], [E_CHAR_PROPS]),
  row('WF-004', '删除线', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'toggle', 'unset'], [E_CHAR_PROPS]),
  row('WF-005', '上标与下标', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-006', '修改字体', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'],
    ['set', 'clear'], [E_CHAR_PROPS], 'ascii/hAnsi/eastAsia/cs 分列；缺失字体只保存指定、不宣称渲染一致。'),
  row('WF-007', '字号', G_CHAR, 'implemented',
    ['src/documents/units/font-size.ts', 'src/documents/operations/character/properties.ts'],
    ['set', 'read'], ['src/documents/units/font-size.test.ts'], '半点值（sz）与中文字号映射表在 units/font-size.ts。'),
  row('WF-008', '增大/减小字号', G_CHAR, 'partial',
    ['src/documents/units/font-size.ts'], ['set', 'read'],
    ['src/documents/units/font-size.test.ts'], '有字号单位与相对步进基础；未确认 UI/工作流层的「增大/减小」入口接线。'),
  row('WF-009', '字体颜色', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-010', '文本高亮', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-011', '字符底纹', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-012', '字符间距', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-013', '字符缩放与位置', G_CHAR, 'implemented',
    ['src/documents/operations/character/properties.ts'], ['set', 'unset'], [E_CHAR_PROPS]),
  row('WF-014', '英文大小写转换', G_CHAR, 'missing',
    [], ['convert'], [],
    '全仓检索无大小写转换实现（无 textTransform/toUpper/toLower 应用于选区）。仅有个别统计/编号处的 toUpperCase。'),
  row('WF-015', '清除字符直接格式', G_CHAR, 'implemented',
    ['src/documents/operations/character/types.ts', 'src/documents/operations/character/apply.ts'],
    ['clear'], [E_CHAR_APPLY], 'types.ts 提供 clearDirectFormat / inherit 操作语义（R117 四态）。'),
  row('WF-016', '格式复制/格式刷', G_CHAR, 'partial',
    ['src/documents/operations/character/read.ts', 'src/documents/operations/character/properties.ts'],
    ['read', 'set'], ['src/documents/operations/character/read.test.ts'], '有属性读回与设置原语；未见独立的「格式刷」工作流入口。'),

  // ── 3.2 段落排版（W1） ─────────────────────────────────────────────
  row('WF-017', '左对齐', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/alignment.ts'], ['set', 'read'],
    ['src/documents/operations/paragraph/alignment.test.ts']),
  row('WF-018', '居中', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/alignment.ts'], ['set', 'read'],
    ['src/documents/operations/paragraph/alignment.test.ts']),
  row('WF-019', '右对齐', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/alignment.ts'], ['set', 'read'],
    ['src/documents/operations/paragraph/alignment.test.ts']),
  row('WF-020', '两端对齐', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/alignment.ts'], ['set', 'read'],
    ['src/documents/operations/paragraph/alignment.test.ts']),
  row('WF-021', '分散对齐', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/alignment.ts'], ['set', 'read'],
    ['src/documents/operations/paragraph/alignment.test.ts']),
  row('WF-022', '单倍/1.5 倍/双倍行距', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/line-spacing.ts', 'src/documents/units/line-spacing.ts'],
    ['set', 'read'], ['src/documents/operations/paragraph/line-spacing.test.ts', 'src/documents/units/line-spacing.test.ts']),
  row('WF-023', '自定义多倍行距', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/line-spacing.ts', 'src/documents/units/line-spacing.ts'],
    ['set', 'read'], ['src/documents/units/line-spacing.test.ts']),
  row('WF-024', '固定值/最小值行距', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/line-spacing.ts', 'src/documents/units/line-spacing.ts'],
    ['set', 'read'], ['src/documents/operations/paragraph/line-spacing.test.ts']),
  row('WF-025', '段前间距', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/spacing.ts', 'src/documents/units/paragraph-spacing.ts'],
    ['set', 'unset', 'read'], ['src/documents/operations/paragraph/spacing.test.ts', 'src/documents/units/paragraph-spacing.test.ts']),
  row('WF-026', '段后间距', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/spacing.ts', 'src/documents/units/paragraph-spacing.ts'],
    ['set', 'unset', 'read'], ['src/documents/operations/paragraph/spacing.test.ts']),
  row('WF-027', '首行缩进', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/indent.ts', 'src/documents/units/indent.ts'],
    ['set', 'unset', 'read'], ['src/documents/operations/paragraph/indent.test.ts', 'src/documents/units/indent.test.ts'],
    '字符单位与长度单位分列（firstLineChars vs firstLine）；禁止用空格模拟。'),
  row('WF-028', '悬挂缩进', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/indent.ts'], ['set', 'unset', 'read'],
    ['src/documents/operations/paragraph/indent.test.ts']),
  row('WF-029', '左右缩进', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/indent.ts', 'src/documents/units/indent.ts'], ['set', 'unset', 'read'],
    ['src/documents/operations/paragraph/indent.test.ts']),
  row('WF-030', '制表位', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/tab-stops.ts', 'src/documents/units/tab-stop.ts'], ['insert', 'delete', 'set'],
    ['src/documents/operations/paragraph/tab-stops.test.ts', 'src/documents/units/tab-stop.test.ts']),
  row('WF-031', '换行与段落拆合', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/breaks.ts'], ['insert', 'delete'], ['src/documents/operations/paragraph/breaks.test.ts']),
  row('WF-032', '分页控制', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/pagination.ts'], ['set'], ['src/documents/operations/paragraph/pagination.test.ts']),
  row('WF-033', '段落边框与底纹', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/borders-shading.ts'], ['set', 'unset'],
    ['src/documents/operations/paragraph/borders-shading.test.ts']),
  row('WF-034', '清除/复制段落格式', G_PARA, 'implemented',
    ['src/documents/operations/paragraph/clear-copy.ts'], ['clear', 'set'],
    ['src/documents/operations/paragraph/clear-copy.test.ts']),

  // ── 3.3 样式、列表与组织（W2） ─────────────────────────────────────
  row('WF-035', '正文/标题/副标题样式', G_STYLE, 'implemented',
    ['src/documents/styles/named.ts', 'src/documents/styles/apply.ts'], ['set', 'link'],
    ['src/documents/styles/named.test.ts']),
  row('WF-036', '多级标题', G_STYLE, 'implemented',
    ['src/documents/styles/outline.ts', 'src/documents/styles/chain.ts'], ['set', 'link'],
    ['src/documents/styles/outline.test.ts']),
  row('WF-037', '自定义/修改样式', G_STYLE, 'implemented',
    ['src/documents/styles/apply.ts', 'src/documents/styles/named.ts'], ['set', 'read'],
    ['src/documents/styles/apply.test.ts']),
  row('WF-038', '样式继承与重置', G_STYLE, 'implemented',
    ['src/documents/styles/cascade.ts', 'src/documents/styles/explain.ts', 'src/documents/styles/run-cascade.ts'],
    ['read', 'clear'], ['src/documents/styles/cascade.test.ts', 'src/documents/styles/explain.test.ts']),
  row('WF-039', '项目符号', G_STYLE, 'implemented',
    ['src/documents/numbering/apply.ts', 'src/documents/numbering/format.ts'], ['set', 'unset'],
    ['src/documents/numbering/apply.test.ts']),
  row('WF-040', '编号列表', G_STYLE, 'implemented',
    ['src/documents/numbering/format.ts', 'src/documents/numbering/apply.ts'], ['set', 'unset'],
    ['src/documents/numbering/format.test.ts']),
  row('WF-041', '多级列表', G_STYLE, 'implemented',
    ['src/documents/numbering/resolve.ts', 'src/documents/numbering/table.ts'], ['set', 'read'],
    ['src/documents/numbering/resolve.test.ts']),
  row('WF-042', '列表重启与续编', G_STYLE, 'implemented',
    ['src/documents/numbering/apply.ts', 'src/documents/numbering/table.ts'], ['set', 'insert'],
    ['src/documents/numbering/apply.test.ts'], 'restartListForParagraphs / continueListForParagraphs 已存在。'),
  row('WF-043', '段落/块移动复制删除', G_STYLE, 'implemented',
    ['src/documents/styles/block-edit.ts'], ['move', 'insert', 'delete'],
    ['src/documents/styles/block-edit.test.ts']),
  row('WF-044', '批量格式修改', G_STYLE, 'implemented',
    ['src/documents/styles/batch-format.ts'], ['set'], ['src/documents/styles/batch-format.test.ts']),

  // ── 3.4 页面与节（W2） ──────────────────────────────────────────────
  row('WF-045', '纸张大小', G_PAGE, 'implemented',
    ['src/documents/sections/page-setup.ts'], ['set', 'read'],
    ['src/documents/sections/page-setup.test.ts']),
  row('WF-046', '横向/纵向', G_PAGE, 'implemented',
    ['src/documents/sections/page-setup.ts'], ['set', 'read'],
    ['src/documents/sections/page-setup.test.ts']),
  row('WF-047', '页边距', G_PAGE, 'implemented',
    ['src/documents/sections/margins.ts', 'src/documents/sections/page-setup.ts'], ['set', 'read'],
    ['src/documents/sections/page-setup.test.ts'], 'margins.ts 无专属 test；由 page-setup.test.ts 间接覆盖。'),
  row('WF-048', '分页符', G_PAGE, 'implemented',
    ['src/documents/sections/breaks.ts', 'src/documents/operations/paragraph/breaks.ts'], ['insert', 'delete'],
    ['src/documents/sections/breaks.test.ts']),
  row('WF-049', '分节符', G_PAGE, 'implemented',
    ['src/documents/sections/section-breaks.ts'], ['insert', 'delete'],
    ['src/documents/sections/section-breaks.test.ts']),
  row('WF-050', '分栏', G_PAGE, 'implemented',
    ['src/documents/sections/columns.ts', 'src/documents/sections/extras.ts'], ['set'],
    ['src/documents/sections/page-setup.test.ts'], 'columns.ts 无专属 test；列宽经 extras/page-setup 覆盖。'),
  row('WF-051', '页眉与页脚', G_PAGE, 'implemented',
    ['src/documents/sections/header-footer.ts', 'src/documents/header-footer-workflow.ts'], ['insert', 'delete', 'set'],
    ['src/documents/sections/header-footer.test.ts', 'src/documents/header-footer-workflow.test.ts']),
  row('WF-052', '首页/奇偶页不同', G_PAGE, 'implemented',
    ['src/documents/sections/header-footer.ts'], ['set'], ['src/documents/sections/header-footer.test.ts']),
  row('WF-053', '页码', G_PAGE, 'implemented',
    ['src/documents/sections/page-numbering.ts'], ['insert', 'generate'],
    ['src/documents/sections/page-numbering.test.ts'], '域指令写入 ≠ 页码已计算；真实页码依赖排版（见 W09/W04）。'),
  row('WF-054', '页面边框/背景/水印', G_PAGE, 'missing',
    ['src/documents/sections/index.ts'], [], [],
    'sections/index.ts 明确声明「不做页面边框 / 背景 / 水印（WF-054）」；未找到实现模块。'),
  row('WF-055', '页内垂直对齐', G_PAGE, 'implemented',
    ['src/documents/sections/vertical-align.ts'], ['set'],
    ['src/documents/sections/page-setup.test.ts']),

  // ── 3.5 表格（W2） ─────────────────────────────────────────────────
  row('WF-056', '插入/删除表格', G_TABLE, 'implemented',
    ['src/documents/operations/table/table-structure.ts'], ['insert', 'delete'],
    ['src/documents/operations/table/table-structure.test.ts']),
  row('WF-057', '增删行列', G_TABLE, 'implemented',
    ['src/documents/operations/table/edit.ts', 'src/documents/operations/table/grid.ts'], ['insert', 'delete'],
    ['src/documents/operations/table/grid.test.ts'], 'edit.ts 无专属 test；行列增删由 grid.test.ts / table-structure.test.ts 覆盖。'),
  row('WF-058', '单元格合并/拆分', G_TABLE, 'implemented',
    ['src/documents/operations/table/merge.ts'], ['insert', 'delete'],
    ['src/documents/operations/table/merge.test.ts']),
  row('WF-059', '列宽/行高', G_TABLE, 'implemented',
    ['src/documents/operations/table/size.ts', 'src/documents/operations/table/layout.ts'], ['set', 'read'],
    ['src/documents/operations/table/size.test.ts']),
  row('WF-060', '表格对齐与定位', G_TABLE, 'implemented',
    ['src/documents/operations/table/layout.ts', 'src/documents/operations/table/extensions.ts'], ['set'],
    ['src/documents/operations/table/properties.test.ts'],
    '表格定位/对齐在 layout.ts 与 extensions.ts（无独立 properties.ts 模块）。'),
  row('WF-061', '单元格内容排版', G_TABLE, 'implemented',
    ['src/documents/operations/table/cell-format.ts'], ['set'],
    ['src/documents/operations/table/properties.test.ts']),
  row('WF-062', '表格边框/底纹/样式', G_TABLE, 'implemented',
    ['src/documents/operations/table/borders.ts'], ['set', 'unset'],
    ['src/documents/operations/table/properties.test.ts']),
  row('WF-063', '表头与跨页行为', G_TABLE, 'implemented',
    ['src/documents/operations/table/layout.ts', 'src/documents/operations/table/grid.ts'], ['set'],
    ['src/documents/operations/table/properties.test.ts'], '重复标题行（tblHeader）在 layout.ts。'),
  row('WF-064', '表格内容编辑', G_TABLE, 'implemented',
    ['src/documents/operations/table/content.ts', 'src/documents/table-workflow.ts'], ['replace', 'convert'],
    ['src/documents/operations/table/content.test.ts', 'src/documents/table-workflow.test.ts']),

  // ── 3.6 图片与图形（W2/W3） ────────────────────────────────────────
  row('WF-065', '插入/替换/删除图片', G_DRAW, 'implemented',
    ['src/documents/operations/drawing/image.ts', 'src/documents/operations/drawing/media.ts'], ['insert', 'replace', 'delete'],
    ['src/documents/operations/drawing/image.test.ts', 'src/documents/operations/drawing/media.test.ts']),
  row('WF-066', '图片尺寸与旋转', G_DRAW, 'implemented',
    ['src/documents/operations/drawing/params.ts'], ['set'], ['src/documents/operations/drawing/image.test.ts']),
  row('WF-067', '图片裁剪', G_DRAW, 'implemented',
    ['src/documents/operations/drawing/params.ts'], ['set'], ['src/documents/operations/drawing/image.test.ts'],
    '保存裁剪参数（srcRect），不把预览裁剪当文件已裁剪。'),
  row('WF-068', '图片环绕与位置', G_DRAW, 'implemented',
    ['src/documents/operations/drawing/params.ts', 'src/documents/operations/drawing/media.ts'], ['set'],
    ['src/documents/operations/drawing/image.test.ts']),
  row('WF-069', '图片描述与题注', G_DRAW, 'partial',
    ['src/documents/operations/drawing/image.ts', 'src/documents/references/crossref.ts'], ['set', 'generate'],
    ['src/documents/operations/drawing/image.test.ts'], '替代文字（docPr descr）与题注编号分散在 drawing/references，未确认端到端接线。'),
  row('WF-070', '文本框及常用形状', G_DRAW, 'implemented',
    ['src/documents/operations/drawing/shape.ts'], ['insert', 'delete', 'set'],
    ['src/documents/operations/drawing/shape.test.ts']),

  // ── 3.7 引用、长文与审阅（W3） ────────────────────────────────────
  row('WF-071', '超链接', G_REF, 'implemented',
    ['src/documents/references/hyperlinks.ts'], ['insert', 'delete', 'link'],
    ['src/documents/references/hyperlinks.test.ts']),
  row('WF-072', '书签', G_REF, 'implemented',
    ['src/documents/references/bookmarks.ts', 'src/documents/references/anchors.ts'], ['insert', 'delete', 'set'],
    ['src/documents/references/bookmarks.test.ts']),
  row('WF-073', '目录', G_REF, 'partial',
    ['src/documents/references/toc.ts'], ['generate'],
    ['src/documents/references/toc.test.ts'], '目录生成存在；真实页码依赖排版引擎（W04/W09），不编造缓存页码。'),
  row('WF-074', '脚注与尾注', G_REF, 'implemented',
    ['src/documents/references/notes.ts'], ['insert', 'delete', 'set'],
    ['src/documents/references/notes.test.ts']),
  row('WF-075', '交叉引用', G_REF, 'implemented',
    ['src/documents/references/crossref.ts'], ['link', 'generate'],
    ['src/documents/references/crossref.test.ts']),
  row('WF-076', '常用域更新', G_REF, 'implemented',
    ['src/documents/references/fields.ts'], ['generate', 'read'],
    ['src/documents/references/fields.test.ts'], '区分域指令 / 缓存 / 实际刷新；写入域 ≠ 已刷新。'),
  row('WF-077', '批注', G_REF, 'implemented',
    ['src/documents/review/comments.ts'], ['insert', 'delete', 'set'],
    ['src/documents/review/comments.test.ts']),
  row('WF-078', '修订记录', G_REF, 'implemented',
    ['src/documents/review/revisions.ts'], ['set', 'insert', 'delete'],
    ['src/documents/review/revisions.test.ts']),
  row('WF-079', '接受/拒绝修订', G_REF, 'implemented',
    ['src/documents/review/accept.ts', 'src/documents/accept-reject.ts'], ['set', 'delete'],
    ['src/documents/review/accept.test.ts', 'src/documents/accept-reject.test.ts']),
  row('WF-080', '版本比较', G_REF, 'implemented',
    ['src/documents/review/compare.ts'], ['compare'],
    ['src/documents/review/compare.test.ts']),

  // ── 3.8 编辑与文件工作流 ──────────────────────────────────────────
  row('WF-081', '新建、重命名与连续编辑', G_FLOW, 'implemented',
    ['src/documents/session/session.ts', 'src/documents/session/list-ops.ts'], ['insert', 'set'],
    ['src/documents/session/session.test.ts']),
  row('WF-082', '导入既有 DOCX', G_FLOW, 'implemented',
    ['src/documents/docx/import.ts'], ['read'],
    ['src/documents/docx/roundtrip.test.ts', 'src/documents/docx/import-column-width.test.ts']),
  row('WF-083', '保存并重新打开', G_FLOW, 'implemented',
    ['src/documents/docx/export.ts', 'src/documents/session/persistence.ts'], ['render'],
    ['src/documents/docx/roundtrip.test.ts', 'src/documents/session/session.test.ts'],
    '电脑侧往返已验；手机杀进程重开未验（真机层空白）。'),
  row('WF-084', '另存/导出副本', G_FLOW, 'implemented',
    ['src/documents/session/canonical.ts', 'src/documents/docx/export.ts'], ['render'],
    ['src/documents/session/session.test.ts']),
  row('WF-085', '查找替换', G_FLOW, 'implemented',
    ['src/documents/selection/find.ts', 'src/documents/operations/character/replace.ts'], ['replace'],
    ['src/documents/selection/find.test.ts', E_CHAR_REPLACE]),
  row('WF-086', '撤销与重做', G_FLOW, 'missing',
    [], ['clear'], [],
    'src/documents 全仓检索无 undo/redo 实现（无对应方法或模块）；W10 计划补齐。'),
  row('WF-087', '版本、并发与失败恢复', G_FLOW, 'implemented',
    ['src/documents/session/session.ts', 'src/artifacts/publish.ts'], ['compare', 'read'],
    ['src/documents/session/session.test.ts', 'src/artifacts/publish.test.ts'],
    'session 有 base_revision 摘要绑定、stale_revision 拒绝、idempotency_conflict。'),
  row('WF-088', '选区、剪贴板与预览', G_FLOW, 'partial',
    ['src/documents/selection/selection.ts', 'src/documents/selection/resolve.ts', 'src/documents/operations/character/apply.ts'],
    ['replace', 'insert'], ['src/documents/selection/selection.test.ts', 'src/documents/selection/resolve.test.ts'],
    '选区/范围解析与替换存在；剪贴板（复制/剪切/粘贴、纯文本粘贴）未见独立模块。'),
  row('WF-089', 'PDF 导出', G_FLOW, 'unverified',
    ['src/mobile-plugins/word/rendering/paginate.ts', 'apps/android/app/src/main/java/com/potbot/demo/PotbotPdfLayout.java'],
    ['render'], [], '手机原生排版子集存在（固定 A4/72pt 边距/段落子集）；无仓内自动化证据，真机 PDF 读回未验。'),
  row('WF-090', '打印交接', G_FLOW, 'unverified',
    ['apps/android/app/src/main/java/com/potbot/demo/PotbotPrintHandoff.java'], ['handoff'], [],
    '打印交接类存在；「交接」不等于已打印，无自动化证据。'),

  // ── 3.9 其他常用内容与校对（W3） ──────────────────────────────────
  row('WF-091', '公式', G_OTHER, 'implemented',
    ['src/documents/equations/omml.ts', 'src/documents/equations/build.ts'], ['insert', 'replace'],
    ['src/documents/equations/equations.test.ts', 'src/documents/equations/inline.test.ts'],
    'OMML 结构化公式；既有复杂公式保留（preserve.ts）。'),
  row('WF-092', '常用图表', G_OTHER, 'implemented',
    ['src/documents/charts/build.ts', 'src/documents/charts/facts.ts'], ['insert', 'set'],
    ['src/documents/charts/charts.test.ts'], '图表嵌入数据表与事实版本一致性在 charts/facts.ts。'),
  row('WF-093', '符号与特殊字符', G_OTHER, 'implemented',
    ['src/documents/proofing/symbols.ts'], ['insert', 'convert'],
    ['src/documents/proofing/symbols.test.ts']),
  row('WF-094', '字数与统计', G_OTHER, 'implemented',
    ['src/documents/proofing/counts.ts'], ['count'],
    ['src/documents/proofing/counts.test.ts'], '中英文/emoji 计数口径；页数须真实排版，不由字符数推算。'),
  row('WF-095', '拼写与语法检查', G_OTHER, 'partial',
    ['src/documents/proofing/spelling.ts'], ['read', 'set'],
    ['src/documents/proofing/spelling.test.ts'], '有拼写检查骨架；「不以固定提示冒充真实检查」——真实模型输出绑定见 W08。'),
  row('WF-096', '文本语言与选区翻译', G_OTHER, 'partial',
    ['src/documents/proofing/language.ts', 'src/documents/proofing/translation.ts', 'src/documents/proofing/port.ts'],
    ['set', 'translate'], ['src/documents/proofing/translation.test.ts', 'src/documents/proofing/port.test.ts'],
    'language.ts 无专属 test（经 translation/port 间接触及）；真实 Flash 输出、revision 绑定与模型预算由 W08 补，当前标 partial。'),
];

/** 便捷索引：WF → 行。 */
export function mappingByWf(rows: readonly WfMappingRow[] = WF_MAPPING): ReadonlyMap<string, WfMappingRow> {
  const map = new Map<string, WfMappingRow>();
  for (const r of rows) map.set(r.wf, r);
  return map;
}
